---
#:skeleton: "Your skeleton key"
#if not defined, there will be no skeleton key (recommended)

#:kannel:
#  :username: opencellpager
#  :password: PASSWORD

# clickatell options:
# note: the from number will need to be registered in your clickatell account in order to be able to send from it
# from is optional
#:clickatell:
#  :api_id: 'ID'
#  :username: 'USERNAME'
#  :password: 'PASSWORD'
#  :from: 'the number you want people to respond to'

:tropo:
  :token: 'your token'
  :assume_north_america: true

#:conversations_timeout: 30 # in minutes

# Uncomment if using heroku
:use_delayed_job: false
